# Generated by Django 4.1.4 on 2022-12-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Description', models.TextField()),
                ('Lat', models.FloatField()),
                ('Lon', models.FloatField()),
            ],
        ),
    ]
