# Generated by Django 4.1.4 on 2022-12-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
