# Generated by Django 4.1.4 on 2022-12-26 10:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0004_delete_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotels_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Description', models.TextField()),
                ('Image_url', models.URLField(default='exit')),
                ('Geopoint', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                
            ],
        ),
    ]
