# Generated by Django 4.1.4 on 2022-12-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels_details',
            name='Image_field',
            field=models.ImageField(default='upload', upload_to='static'),
        ),
    ]
